import { Customer, Payment, RecoveryCase, AgentDecision, IntegrationSource, RecoveryKPIData } from './types';

export const INITIAL_KPIS: RecoveryKPIData = {
  revenueAtRisk: 1842000, // ₹18.42L
  recovering: 684000,     // ₹6.84L
  recovered: 724000,      // ₹7.24L (HERO METRIC)
  recoveryRate: 39.3,     // 39.3%
  activeCasesCount: 143,  // 143 active cases
  trendVsLastMonth: 18.4, // +18.4%
  eventsProcessed: 1248,
  actionsTaken: 312,
};

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: 'cust-acme',
    name: 'Rohan Sharma',
    company: 'Acme Corp',
    email: 'finance@acmecorp.in',
    phone: '+91 98201 44821',
    customerType: 'Enterprise',
    lifetimeValue: 480000, // ₹4.8L LTV
    paymentHistory: {
      successfulCount: 8,
      failedCount: 0,
      lastPaymentDate: '2026-07-20T10:00:00Z',
      avgTicketSize: 24999,
    },
    preferredChannel: 'whatsapp',
    accountManager: 'Priya Mehta',
  },
  {
    id: 'cust-nova',
    name: 'Ananya Deshmukh',
    company: 'Nova Systems',
    email: 'billing@novasystems.io',
    phone: '+91 97110 55290',
    customerType: 'Mid-Market',
    lifetimeValue: 320000,
    paymentHistory: {
      successfulCount: 14,
      failedCount: 1,
      lastPaymentDate: '2026-07-15T09:30:00Z',
      avgTicketSize: 15499,
    },
    preferredChannel: 'email',
    accountManager: 'Vikram Seth',
  },
  {
    id: 'cust-globex',
    name: 'Siddharth Varma',
    company: 'Globex Pvt Ltd',
    email: 'accounts@globexindia.com',
    phone: '+91 98450 11928',
    customerType: 'Enterprise',
    lifetimeValue: 690000,
    paymentHistory: {
      successfulCount: 11,
      failedCount: 1,
      lastPaymentDate: '2026-07-18T14:10:00Z',
      avgTicketSize: 48999,
    },
    preferredChannel: 'payment_link',
    accountManager: 'Priya Mehta',
  },
  {
    id: 'cust-zenith',
    name: 'Kavita Nair',
    company: 'Zenith Inc.',
    email: 'payments@zenithcommerce.co',
    phone: '+91 99203 77481',
    customerType: 'Mid-Market',
    lifetimeValue: 285000,
    paymentHistory: {
      successfulCount: 5,
      failedCount: 1,
      lastPaymentDate: '2026-06-22T11:00:00Z',
      avgTicketSize: 32799,
    },
    preferredChannel: 'phone',
    accountManager: 'Karan Joshi',
  },
  {
    id: 'cust-innotech',
    name: 'Arjun Singhania',
    company: 'Innotech Solutions',
    email: 'treasury@innotech.ai',
    phone: '+91 98100 88231',
    customerType: 'Enterprise',
    lifetimeValue: 1450000,
    paymentHistory: {
      successfulCount: 18,
      failedCount: 2,
      lastPaymentDate: '2026-07-10T16:00:00Z',
      avgTicketSize: 124000,
    },
    preferredChannel: 'whatsapp',
    accountManager: 'Vikram Seth',
  },
  {
    id: 'cust-quantlog',
    name: 'Devika Rao',
    company: 'QuantLog Analytics',
    email: 'finance@quantlog.com',
    phone: '+91 98332 99011',
    customerType: 'Enterprise',
    lifetimeValue: 890000,
    paymentHistory: {
      successfulCount: 9,
      failedCount: 0,
      lastPaymentDate: '2026-08-19T13:42:00Z',
      avgTicketSize: 89000,
    },
    preferredChannel: 'whatsapp',
    accountManager: 'Priya Mehta',
  },
  {
    id: 'cust-vortex',
    name: 'Sameer Patel',
    company: 'Vortex SaaS',
    email: 'billing@vortex.dev',
    phone: '+91 97654 32100',
    customerType: 'SMB',
    lifetimeValue: 160000,
    paymentHistory: {
      successfulCount: 12,
      failedCount: 0,
      lastPaymentDate: '2026-08-18T10:15:00Z',
      avgTicketSize: 12999,
    },
    preferredChannel: 'payment_link',
  },
  {
    id: 'cust-alphastream',
    name: 'Gaurav Kulkarni',
    company: 'AlphaStream Media',
    email: 'admin@alphastream.in',
    phone: '+91 99887 76655',
    customerType: 'Enterprise',
    lifetimeValue: 520000,
    paymentHistory: {
      successfulCount: 4,
      failedCount: 3,
      lastPaymentDate: '2026-06-01T15:00:00Z',
      avgTicketSize: 78000,
    },
    preferredChannel: 'email',
    accountManager: 'Karan Joshi',
  },
];

export const INITIAL_CASES: RecoveryCase[] = [
  {
    id: 'case-acme-10291',
    customerId: 'cust-acme',
    customer: DEMO_CUSTOMERS[0],
    paymentId: 'pay_rzp_acme_10291',
    payment: {
      id: 'pay_rzp_acme_10291',
      customerId: 'cust-acme',
      amount: 24999,
      currency: 'INR',
      status: 'failed',
      failureReason: 'Insufficient funds',
      attemptCount: 1,
      provider: 'Razorpay Sandbox',
      createdAt: '2026-08-21T11:42:00Z',
      updatedAt: '2026-08-21T11:43:00Z',
    },
    amount: 24999,
    status: 'at_risk',
    riskScore: 'Low',
    recoveryProbability: 82,
    rootCause: 'Insufficient funds',
    recommendedAction: 'Retry payment tomorrow at 10:00 AM',
    interventionType: 'retry_payment',
    currentAction: 'Pending approval & schedule',
    nextAction: 'Execute smart retry at optimal window',
    scheduledTime: 'Tomorrow, 10:00 AM',
    attemptsUsed: 0,
    contactAttemptsUsed: 0,
    createdAt: '2026-08-21T11:42:00Z',
    updatedAt: '2026-08-21T11:43:00Z',
    decision: {
      id: 'dec-10291',
      caseId: 'case-acme-10291',
      paymentId: 'pay_rzp_acme_10291',
      recommendedAction: 'Retry payment tomorrow at 10:00 AM',
      interventionType: 'retry_payment',
      recoveryProbability: 82,
      explanation: 'This is the customer\'s first failure and their historical payment behavior indicates a high probability of recovery.',
      rationaleItems: [
        { text: 'First payment failure (clean history)', passed: true, type: 'history' },
        { text: 'Strong payment history (8 successful payments)', passed: true, type: 'history' },
        { text: 'High customer lifetime value (₹4.8L LTV)', passed: true, type: 'value' },
        { text: 'Retry limit available (0/2 attempts used)', passed: true, type: 'guardrail' },
        { text: 'Optimal retry window (next business morning)', passed: true, type: 'timing' },
      ],
      status: 'pending',
      createdAt: '2026-08-21T11:43:00Z',
    },
    timeline: [
      {
        id: 'tl-1',
        timestamp: '13:42:01',
        actor: 'System',
        event: 'Payment failure detected',
        toolUsed: 'webhook_receiver',
        details: 'Received Razorpay failure webhook (code: INSUFFICIENT_FUNDS)',
        status: 'completed',
        state: 'DETECTING' as any,
      },
      {
        id: 'tl-2',
        timestamp: '13:42:02',
        actor: 'Reclaim Agent',
        event: 'Customer history retrieved',
        toolUsed: 'get_customer_profile',
        details: 'Fetched 8 successful past cycles, zero past failures. LTV: ₹4.8L.',
        status: 'completed',
        state: 'ANALYZING',
      },
      {
        id: 'tl-3',
        timestamp: '13:42:03',
        actor: 'Reclaim Agent',
        event: 'Recovery probability calculated',
        toolUsed: 'calculate_recovery_probability',
        details: 'Model estimated 82% recovery probability based on salary cycle & liquidity timing.',
        result: '82% probability',
        status: 'completed',
        state: 'DECIDING',
      },
      {
        id: 'tl-4',
        timestamp: '13:43:00',
        actor: 'Reclaim Agent',
        event: 'Recovery strategy selected',
        toolUsed: 'select_intervention',
        details: 'Selected smart retry for tomorrow 10:00 AM within guardrails.',
        status: 'completed',
        state: 'WAITING',
      },
    ],
    guardrailChecks: {
      retryLimitPassed: true,
      contactLimitPassed: true,
      quietHoursPassed: true,
      recoveryWindowPassed: true,
      highValueApprovalRequired: false,
    },
  },
  {
    id: 'case-nova-10292',
    customerId: 'cust-nova',
    customer: DEMO_CUSTOMERS[1],
    paymentId: 'pay_rzp_nova_10292',
    amount: 15499,
    status: 'recovering',
    riskScore: 'Medium',
    recoveryProbability: 76,
    rootCause: 'Card expired',
    recommendedAction: 'Send payment method update link via WhatsApp',
    interventionType: 'request_payment_method_update',
    currentAction: 'Waiting for card update',
    nextAction: 'Auto-charge updated card upon submission',
    attemptsUsed: 1,
    contactAttemptsUsed: 1,
    createdAt: '2026-08-21T09:15:00Z',
    updatedAt: '2026-08-21T09:20:00Z',
    payment: {
      id: 'pay_rzp_nova_10292',
      customerId: 'cust-nova',
      amount: 15499,
      currency: 'INR',
      status: 'failed',
      failureReason: 'Card expired',
      attemptCount: 1,
      provider: 'Razorpay Sandbox',
      createdAt: '2026-08-21T09:15:00Z',
      updatedAt: '2026-08-21T09:20:00Z',
    },
    decision: {
      id: 'dec-10292',
      caseId: 'case-nova-10292',
      paymentId: 'pay_rzp_nova_10292',
      recommendedAction: 'Request payment method update',
      interventionType: 'request_payment_method_update',
      recoveryProbability: 76,
      explanation: 'Card expiry detected. Instant retry would fail; sending secure 1-click update link has 76% conversion within 4 hours.',
      rationaleItems: [
        { text: 'Card expiration confirmed by gateway', passed: true, type: 'risk' },
        { text: '14 successful past payments on file', passed: true, type: 'history' },
        { text: 'Contact limit within guardrails (1/3)', passed: true, type: 'guardrail' },
      ],
      status: 'executing',
      createdAt: '2026-08-21T09:16:00Z',
    },
    timeline: [
      {
        id: 'tl-n1',
        timestamp: '09:15:10',
        actor: 'System',
        event: 'Payment failure detected',
        toolUsed: 'webhook_receiver',
        details: 'Card expired (07/26)',
        status: 'completed',
        state: 'ANALYZING',
      },
      {
        id: 'tl-n2',
        timestamp: '09:16:00',
        actor: 'Reclaim Agent',
        event: 'Generated secure payment method link',
        toolUsed: 'create_payment_link',
        details: 'Created Razorpay compliant update token',
        status: 'completed',
        state: 'ACTING',
      },
      {
        id: 'tl-n3',
        timestamp: '09:16:30',
        actor: 'Reclaim Agent',
        event: 'WhatsApp notification dispatched',
        toolUsed: 'send_whatsapp_message',
        details: 'Sent 1-click payment update link to Ananya Deshmukh',
        status: 'completed',
        state: 'WAITING',
      },
    ],
    guardrailChecks: {
      retryLimitPassed: true,
      contactLimitPassed: true,
      quietHoursPassed: true,
      recoveryWindowPassed: true,
      highValueApprovalRequired: false,
    },
  },
  {
    id: 'case-globex-10293',
    customerId: 'cust-globex',
    customer: DEMO_CUSTOMERS[2],
    paymentId: 'pay_rzp_globex_10293',
    amount: 48999,
    status: 'recovering',
    riskScore: 'Low',
    recoveryProbability: 72,
    rootCause: 'Insufficient funds',
    recommendedAction: 'Retry payment at 14:00 today',
    interventionType: 'retry_payment',
    currentAction: 'Scheduled retry queued',
    nextAction: 'Execute gateway retry',
    attemptsUsed: 0,
    contactAttemptsUsed: 0,
    createdAt: '2026-08-21T08:30:00Z',
    updatedAt: '2026-08-21T08:35:00Z',
    payment: {
      id: 'pay_rzp_globex_10293',
      customerId: 'cust-globex',
      amount: 48999,
      currency: 'INR',
      status: 'failed',
      failureReason: 'Insufficient funds',
      attemptCount: 1,
      provider: 'Razorpay Sandbox',
      createdAt: '2026-08-21T08:30:00Z',
      updatedAt: '2026-08-21T08:35:00Z',
    },
    decision: {
      id: 'dec-10293',
      caseId: 'case-globex-10293',
      paymentId: 'pay_rzp_globex_10293',
      recommendedAction: 'Retry payment at 14:00 today',
      interventionType: 'retry_payment',
      recoveryProbability: 72,
      explanation: 'High value client with regular afternoon clearing cycles. Automated retry scheduled for 2:00 PM.',
      rationaleItems: [
        { text: 'LTV ₹6.9L enterprise tier', passed: true, type: 'value' },
        { text: 'Zero previous unpaid defaults', passed: true, type: 'history' },
        { text: 'Within single-attempt retry limit', passed: true, type: 'guardrail' },
      ],
      status: 'approved',
      createdAt: '2026-08-21T08:32:00Z',
    },
    timeline: [
      {
        id: 'tl-g1',
        timestamp: '08:30:12',
        actor: 'System',
        event: 'Payment failed at gateway',
        details: 'Insufficient funds reported',
        status: 'completed',
        state: 'ANALYZING',
      },
      {
        id: 'tl-g2',
        timestamp: '08:32:00',
        actor: 'Reclaim Agent',
        event: 'Retry scheduled for 14:00',
        toolUsed: 'retry_payment',
        details: 'Calculated optimal clearing hour',
        status: 'completed',
        state: 'WAITING',
      },
    ],
    guardrailChecks: {
      retryLimitPassed: true,
      contactLimitPassed: true,
      quietHoursPassed: true,
      recoveryWindowPassed: true,
      highValueApprovalRequired: false,
    },
  },
  {
    id: 'case-zenith-10294',
    customerId: 'cust-zenith',
    customer: DEMO_CUSTOMERS[3],
    paymentId: 'pay_rzp_zenith_10294',
    amount: 32799,
    status: 'at_risk',
    riskScore: 'Medium',
    recoveryProbability: 68,
    rootCause: 'Bank decline',
    recommendedAction: 'Contact account owner & provide UPI/NetBanking fallback link',
    interventionType: 'generate_payment_link',
    currentAction: 'Pending link generation',
    nextAction: 'Deliver smart multi-rail payment link',
    attemptsUsed: 1,
    contactAttemptsUsed: 0,
    createdAt: '2026-08-21T07:15:00Z',
    updatedAt: '2026-08-21T07:20:00Z',
    payment: {
      id: 'pay_rzp_zenith_10294',
      customerId: 'cust-zenith',
      amount: 32799,
      currency: 'INR',
      status: 'failed',
      failureReason: 'Bank decline',
      attemptCount: 1,
      provider: 'Razorpay Sandbox',
      createdAt: '2026-08-21T07:15:00Z',
      updatedAt: '2026-08-21T07:20:00Z',
    },
    decision: {
      id: 'dec-10294',
      caseId: 'case-zenith-10294',
      paymentId: 'pay_rzp_zenith_10294',
      recommendedAction: 'Deliver alternative UPI/NetBanking payment link',
      interventionType: 'generate_payment_link',
      recoveryProbability: 68,
      explanation: 'Corporate card declined by issuing bank. Multi-rail payment link enables immediate alternate UPI/NetBanking authorization.',
      rationaleItems: [
        { text: 'Corporate card limit restriction', passed: true, type: 'risk' },
        { text: 'Account active for 18 months', passed: true, type: 'history' },
      ],
      status: 'pending',
      createdAt: '2026-08-21T07:18:00Z',
    },
    timeline: [
      {
        id: 'tl-z1',
        timestamp: '07:15:00',
        actor: 'System',
        event: 'Bank decline received',
        details: 'Error code: 51 - Decline by issuer',
        status: 'completed',
        state: 'ANALYZING',
      },
    ],
    guardrailChecks: {
      retryLimitPassed: true,
      contactLimitPassed: true,
      quietHoursPassed: true,
      recoveryWindowPassed: true,
      highValueApprovalRequired: false,
    },
  },
  {
    id: 'case-innotech-10295',
    customerId: 'cust-innotech',
    customer: DEMO_CUSTOMERS[4],
    paymentId: 'pay_rzp_innotech_10295',
    amount: 124000,
    status: 'at_risk',
    riskScore: 'High',
    recoveryProbability: 59,
    rootCause: 'Mandate failure',
    recommendedAction: 'Notify Account Manager (Vikram Seth) & schedule bounded mandate retry',
    interventionType: 'notify_account_manager',
    currentAction: 'Awaiting high-value human approval (₹1.24L > ₹50,000 threshold)',
    nextAction: 'Escalate to account manager',
    attemptsUsed: 0,
    contactAttemptsUsed: 0,
    createdAt: '2026-08-21T06:00:00Z',
    updatedAt: '2026-08-21T06:05:00Z',
    payment: {
      id: 'pay_rzp_innotech_10295',
      customerId: 'cust-innotech',
      amount: 124000,
      currency: 'INR',
      status: 'failed',
      failureReason: 'Mandate failure',
      attemptCount: 1,
      provider: 'Razorpay Sandbox',
      createdAt: '2026-08-21T06:00:00Z',
      updatedAt: '2026-08-21T06:05:00Z',
    },
    decision: {
      id: 'dec-10295',
      caseId: 'case-innotech-10295',
      paymentId: 'pay_rzp_innotech_10295',
      recommendedAction: 'High-value escalation: Notify Account Manager Vikram Seth',
      interventionType: 'notify_account_manager',
      recoveryProbability: 59,
      explanation: 'Mandate limit cap breached on recurring invoice of ₹1.24L. Guardrail requires human sign-off before customer contact.',
      rationaleItems: [
        { text: 'High-value threshold exceeded (₹1.24L > ₹50k)', passed: false, type: 'guardrail' },
        { text: 'e-Mandate token renewal required', passed: true, type: 'risk' },
        { text: 'Enterprise LTV ₹14.5L', passed: true, type: 'value' },
      ],
      status: 'pending',
      createdAt: '2026-08-21T06:02:00Z',
    },
    timeline: [
      {
        id: 'tl-i1',
        timestamp: '06:00:10',
        actor: 'System',
        event: 'Mandate authorization failed',
        details: 'Recurring e-mandate limit exceeded (Limit: ₹1,00,000)',
        status: 'completed',
        state: 'ANALYZING',
      },
      {
        id: 'tl-i2',
        timestamp: '06:02:00',
        actor: 'Reclaim Agent',
        event: 'Guardrail check paused autonomous action',
        toolUsed: 'check_guardrails',
        details: 'Amount ₹1,24,000 exceeds autonomous ₹50,000 limit. Approval requested.',
        status: 'completed',
        state: 'WAITING',
      },
    ],
    guardrailChecks: {
      retryLimitPassed: true,
      contactLimitPassed: true,
      quietHoursPassed: true,
      recoveryWindowPassed: true,
      highValueApprovalRequired: true,
    },
  },
  {
    id: 'case-quantlog-10288',
    customerId: 'cust-quantlog',
    customer: DEMO_CUSTOMERS[5],
    paymentId: 'pay_rzp_quantlog_10288',
    amount: 89000,
    status: 'recovered',
    riskScore: 'Low',
    recoveryProbability: 91,
    rootCause: 'Invoice overdue',
    recommendedAction: 'WhatsApp reminder with 1-click RTGS/UPI link',
    interventionType: 'send_whatsapp_reminder',
    currentAction: 'Payment successful',
    nextAction: 'Workflow stopped',
    attemptsUsed: 1,
    contactAttemptsUsed: 1,
    recoveredAmount: 89000,
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-08-20T14:22:00Z',
    payment: {
      id: 'pay_rzp_quantlog_10288',
      customerId: 'cust-quantlog',
      amount: 89000,
      currency: 'INR',
      status: 'success',
      failureReason: 'Invoice overdue',
      attemptCount: 1,
      provider: 'Razorpay Sandbox',
      createdAt: '2026-08-20T10:00:00Z',
      updatedAt: '2026-08-20T14:22:00Z',
    },
    decision: {
      id: 'dec-10288',
      caseId: 'case-quantlog-10288',
      paymentId: 'pay_rzp_quantlog_10288',
      recommendedAction: 'WhatsApp reminder with 1-click RTGS/UPI link',
      interventionType: 'send_whatsapp_reminder',
      recoveryProbability: 91,
      explanation: 'Overdue invoice recovered within 4 hours of gentle WhatsApp reminder to Devika Rao.',
      rationaleItems: [
        { text: 'Customer verified active', passed: true, type: 'history' },
        { text: 'Direct WhatsApp preferred channel', passed: true, type: 'timing' },
      ],
      status: 'completed',
      createdAt: '2026-08-20T10:02:00Z',
      executedAt: '2026-08-20T10:05:00Z',
      outcome: 'Payment confirmed via NetBanking webhook. ₹89,000 recovered.',
      recoveredAmount: 89000,
    },
    timeline: [
      {
        id: 'tl-q1',
        timestamp: '10:00:00',
        actor: 'System',
        event: 'Invoice due date expired',
        details: 'Invoice #INV-2026-881 overdue by 2 days',
        status: 'completed',
        state: 'ANALYZING',
      },
      {
        id: 'tl-q2',
        timestamp: '10:05:00',
        actor: 'Reclaim Agent',
        event: 'WhatsApp invoice reminder sent',
        toolUsed: 'send_whatsapp_reminder',
        details: 'Delivered customized payment link to Devika Rao',
        status: 'completed',
        state: 'ACTING',
      },
      {
        id: 'tl-q3',
        timestamp: '14:22:15',
        actor: 'System',
        event: 'Payment webhook received: SUCCESS',
        toolUsed: 'verify_payment_outcome',
        details: '₹89,000 received via Razorpay NetBanking',
        result: '₹89,000 recovered',
        status: 'completed',
        state: 'RECOVERED',
      },
      {
        id: 'tl-q4',
        timestamp: '14:22:16',
        actor: 'Reclaim Agent',
        event: 'Workflow automatically stopped',
        toolUsed: 'stop_workflow',
        details: 'Recovery objective fulfilled. No further contact scheduled.',
        status: 'completed',
        state: 'STOPPED',
      },
    ],
    guardrailChecks: {
      retryLimitPassed: true,
      contactLimitPassed: true,
      quietHoursPassed: true,
      recoveryWindowPassed: true,
      highValueApprovalRequired: false,
    },
  },
  {
    id: 'case-alphastream-10280',
    customerId: 'cust-alphastream',
    customer: DEMO_CUSTOMERS[7],
    paymentId: 'pay_rzp_alpha_10280',
    amount: 78000,
    status: 'escalated',
    riskScore: 'Critical',
    recoveryProbability: 34,
    rootCause: 'Bank decline',
    recommendedAction: 'Escalate to Senior CSM Karan Joshi for direct billing reconciliation',
    interventionType: 'human_escalation',
    currentAction: 'Assigned to Karan Joshi',
    nextAction: 'Manual executive resolution',
    attemptsUsed: 2,
    contactAttemptsUsed: 3,
    createdAt: '2026-08-19T08:00:00Z',
    updatedAt: '2026-08-20T16:00:00Z',
    payment: {
      id: 'pay_rzp_alpha_10280',
      customerId: 'cust-alphastream',
      amount: 78000,
      currency: 'INR',
      status: 'failed',
      failureReason: 'Bank decline',
      attemptCount: 2,
      provider: 'Razorpay Sandbox',
      createdAt: '2026-08-19T08:00:00Z',
      updatedAt: '2026-08-20T16:00:00Z',
    },
    decision: {
      id: 'dec-10280',
      caseId: 'case-alphastream-10280',
      paymentId: 'pay_rzp_alpha_10280',
      recommendedAction: 'Escalate to Senior CSM Karan Joshi',
      interventionType: 'human_escalation',
      recoveryProbability: 34,
      explanation: 'Case reached guardrail boundaries (2 retries + 3 reminders completed). Autonomous agent stopped to prevent customer spam.',
      rationaleItems: [
        { text: 'Max retry limit reached (2/2)', passed: false, type: 'guardrail' },
        { text: 'Max contact attempts reached (3/3)', passed: false, type: 'guardrail' },
        { text: 'Escalation policy triggered', passed: true, type: 'guardrail' },
      ],
      status: 'escalated',
      createdAt: '2026-08-20T16:00:00Z',
    },
    timeline: [
      {
        id: 'tl-a1',
        timestamp: 'Aug 19, 08:00',
        actor: 'System',
        event: 'Payment failed (Attempt 1)',
        details: 'Bank decline on auto-debit',
        status: 'completed',
        state: 'ANALYZING',
      },
      {
        id: 'tl-a2',
        timestamp: 'Aug 19, 14:00',
        actor: 'Reclaim Agent',
        event: 'Smart retry executed (Attempt 2)',
        toolUsed: 'retry_payment',
        details: 'Retry returned: Insufficient limit on corporate card',
        status: 'failed',
        state: 'ACTING',
      },
      {
        id: 'tl-a3',
        timestamp: 'Aug 20, 16:00',
        actor: 'Reclaim Agent',
        event: 'Guardrail limit reached — Escalated to Human',
        toolUsed: 'escalate_case',
        details: 'Assigned to Karan Joshi. Autonomous agent safely paused.',
        status: 'completed',
        state: 'ESCALATED',
      },
    ],
    guardrailChecks: {
      retryLimitPassed: false,
      contactLimitPassed: false,
      quietHoursPassed: true,
      recoveryWindowPassed: true,
      highValueApprovalRequired: true,
    },
  },
];

export const DEMO_INTEGRATIONS: IntegrationSource[] = [
  {
    id: 'int-rzp',
    name: 'Razorpay Sandbox',
    type: 'payment',
    provider: 'Razorpay (Sandbox)',
    status: 'connected',
    isSandbox: true,
    description: 'Payment events, transaction status feeds, webhooks, and recovery opportunities.',
    eventsCount: 127,
    lastSync: 'Just now',
    iconName: 'CreditCard',
  },
  {
    id: 'int-billing',
    name: 'Reclaim Billing',
    type: 'billing',
    provider: 'Reclaim Engine (Billing)',
    status: 'connected',
    isSandbox: true,
    description: 'Subscriptions, invoices, renewals, and overdue payment detection.',
    eventsCount: 84,
    lastSync: '2m ago',
    iconName: 'FileText',
  },
  {
    id: 'int-bank',
    name: 'Business Bank — Sandbox',
    type: 'bank',
    provider: 'HDFC Bank (Sandbox •••• 4821)',
    status: 'connected',
    isSandbox: true,
    description: 'Transaction verification, bank clearance status, and financial context.',
    eventsCount: 184,
    lastSync: 'Just now',
    iconName: 'Building',
  },
  {
    id: 'int-email',
    name: 'Email Recovery Channel',
    type: 'channel',
    provider: 'Direct SMTP / SendGrid',
    status: 'connected',
    isSandbox: true,
    description: 'Automated high-deliverability payment reminders and recovery links.',
    eventsCount: 52,
    lastSync: '5m ago',
    iconName: 'Mail',
  },
  {
    id: 'int-wa',
    name: 'WhatsApp Sandbox',
    type: 'channel',
    provider: 'Meta Cloud API (Sandbox)',
    status: 'not_connected',
    isSandbox: true,
    description: 'Customer recovery messaging and interactive 1-click update links.',
    eventsCount: 0,
    lastSync: 'Never',
    iconName: 'MessageSquare',
  },
  {
    id: 'int-crm',
    name: 'HubSpot / Salesforce CRM',
    type: 'crm',
    provider: 'Salesforce (Mock)',
    status: 'not_connected',
    isSandbox: true,
    description: 'Synchronizes customer health scores, deal size, and account manager assignments.',
    eventsCount: 0,
    lastSync: 'Never',
    iconName: 'Users',
  },
];
