import { Customer, Payment, RecoveryCase, AgentDecision, IntegrationSource, RecoveryKPIData } from './types';
import { generateSyntheticCases } from './simulation-engine';

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: 'cust-acme',
    name: 'Rohan Sharma',
    company: 'Acme Corp',
    email: 'finance@acmecorp.in',
    phone: '+91 98201 44821',
    customerType: 'Enterprise',
    lifetimeValue: 480000, // ₹4.8L LTV
    paymentHistory: {
      successfulCount: 8,
      failedCount: 0,
      lastPaymentDate: '2026-07-20T10:00:00Z',
      avgTicketSize: 24999,
    },
    preferredChannel: 'whatsapp',
    accountManager: 'Priya Mehta',
  },
  {
    id: 'cust-rahul',
    name: 'Rahul Sharma',
    company: 'NextGen Retail',
    email: 'rahul.sharma@nextgenretail.in',
    phone: '+91 98112 33445',
    customerType: 'Mid-Market',
    lifetimeValue: 185000,
    paymentHistory: {
      successfulCount: 6,
      failedCount: 1,
      lastPaymentDate: '2026-08-10T14:30:00Z',
      avgTicketSize: 12999,
    },
    preferredChannel: 'whatsapp',
    accountManager: 'Vikram Seth',
  },
  {
    id: 'cust-acme-tech',
    name: 'Vikrant Goel',
    company: 'Acme Technologies',
    email: 'treasury@acmetechnologies.io',
    phone: '+91 98765 43210',
    customerType: 'Enterprise',
    lifetimeValue: 1250000,
    paymentHistory: {
      successfulCount: 12,
      failedCount: 1,
      lastPaymentDate: '2026-06-30T11:00:00Z',
      avgTicketSize: 240000,
    },
    preferredChannel: 'email',
    accountManager: 'Priya Mehta',
  },
  {
    id: 'cust-nova',
    name: 'Ananya Deshmukh',
    company: 'Nova Systems',
    email: 'billing@novasystems.io',
    phone: '+91 97110 55290',
    customerType: 'Mid-Market',
    lifetimeValue: 320000,
    paymentHistory: {
      successfulCount: 14,
      failedCount: 1,
      lastPaymentDate: '2026-07-15T09:30:00Z',
      avgTicketSize: 15499,
    },
    preferredChannel: 'email',
    accountManager: 'Vikram Seth',
  },
  {
    id: 'cust-globex',
    name: 'Siddharth Varma',
    company: 'Globex Pvt Ltd',
    email: 'accounts@globexindia.com',
    phone: '+91 98450 11928',
    customerType: 'Enterprise',
    lifetimeValue: 690000,
    paymentHistory: {
      successfulCount: 11,
      failedCount: 1,
      lastPaymentDate: '2026-07-18T14:10:00Z',
      avgTicketSize: 48999,
    },
    preferredChannel: 'payment_link',
    accountManager: 'Priya Mehta',
  },
  {
    id: 'cust-zenith',
    name: 'Kavita Nair',
    company: 'Zenith Inc.',
    email: 'payments@zenithcommerce.co',
    phone: '+91 99203 77481',
    customerType: 'Mid-Market',
    lifetimeValue: 285000,
    paymentHistory: {
      successfulCount: 5,
      failedCount: 1,
      lastPaymentDate: '2026-06-22T11:00:00Z',
      avgTicketSize: 32799,
    },
    preferredChannel: 'phone',
    accountManager: 'Karan Joshi',
  },
  {
    id: 'cust-innotech',
    name: 'Arjun Singhania',
    company: 'Innotech Solutions',
    email: 'treasury@innotech.ai',
    phone: '+91 98100 88231',
    customerType: 'Enterprise',
    lifetimeValue: 1450000,
    paymentHistory: {
      successfulCount: 18,
      failedCount: 2,
      lastPaymentDate: '2026-07-10T16:00:00Z',
      avgTicketSize: 124000,
    },
    preferredChannel: 'whatsapp',
    accountManager: 'Vikram Seth',
  },
  {
    id: 'cust-quantlog',
    name: 'Devika Rao',
    company: 'QuantLog Analytics',
    email: 'finance@quantlog.com',
    phone: '+91 98332 99011',
    customerType: 'Enterprise',
    lifetimeValue: 890000,
    paymentHistory: {
      successfulCount: 9,
      failedCount: 0,
      lastPaymentDate: '2026-08-19T13:42:00Z',
      avgTicketSize: 89000,
    },
    preferredChannel: 'whatsapp',
    accountManager: 'Priya Mehta',
  },
  {
    id: 'cust-vortex',
    name: 'Sameer Patel',
    company: 'Vortex SaaS',
    email: 'billing@vortex.dev',
    phone: '+91 97654 32100',
    customerType: 'SMB',
    lifetimeValue: 160000,
    paymentHistory: {
      successfulCount: 12,
      failedCount: 0,
      lastPaymentDate: '2026-08-18T10:15:00Z',
      avgTicketSize: 12999,
    },
    preferredChannel: 'payment_link',
  },
  {
    id: 'cust-alphastream',
    name: 'Gaurav Kulkarni',
    company: 'AlphaStream Media',
    email: 'admin@alphastream.in',
    phone: '+91 99887 76655',
    customerType: 'Enterprise',
    lifetimeValue: 520000,
    paymentHistory: {
      successfulCount: 4,
      failedCount: 3,
      lastPaymentDate: '2026-06-01T15:00:00Z',
      avgTicketSize: 78000,
    },
    preferredChannel: 'email',
    accountManager: 'Karan Joshi',
  },
];

// ─── Primary Showcase Demo Cases (Polished End-to-End Scenarios) ───────────────

const SHOWCASE_CASES: RecoveryCase[] = [
  // 1. Payment Demo: Acme Corp (Insufficient Funds -> Smart Retry)
  {
    id: 'case-acme-10291',
    customerId: 'cust-acme',
    customer: DEMO_CUSTOMERS[0],
    paymentId: 'pay_rzp_acme_10291',
    revenueType: 'payment',
    eventId: 'evt_pay_acme_10291',
    payment: {
      id: 'pay_rzp_acme_10291',
      customerId: 'cust-acme',
      amount: 24999,
      currency: 'INR',
      status: 'failed',
      failureReason: 'Insufficient funds',
      attemptCount: 1,
      provider: 'Razorpay Sandbox',
      createdAt: '2026-08-21T11:42:00Z',
      updatedAt: '2026-08-21T11:43:00Z',
    },
    amount: 24999,
    status: 'at_risk',
    riskScore: 'Low',
    recoveryProbability: 82,
    rootCause: 'Insufficient funds',
    recommendedAction: 'Retry payment tomorrow at 10:00 AM',
    interventionType: 'retry_payment',
    currentAction: 'Pending approval & schedule',
    nextAction: 'Execute smart retry at optimal window',
    scheduledTime: 'Tomorrow, 10:00 AM',
    attemptsUsed: 0,
    contactAttemptsUsed: 0,
    createdAt: '2026-08-21T11:42:00Z',
    updatedAt: '2026-08-21T11:43:00Z',
    decision: {
      id: 'dec-10291',
      caseId: 'case-acme-10291',
      paymentId: 'pay_rzp_acme_10291',
      recommendedAction: 'Retry payment tomorrow at 10:00 AM',
      interventionType: 'retry_payment',
      recoveryProbability: 82,
      expectedRecoveryValue: 20499,
      explanation: 'First payment failure with 8 consecutive historical clearings. Scheduled smart retry yields the highest expected recovery value (₹20,499) within configured boundaries.',
      recoveryOptions: [
        { intervention: 'retry_payment', label: 'Smart Gateway Retry', probability: 82, expectedValue: 20499, rationale: '82% probability · ₹20,499 expected' },
        { intervention: 'generate_payment_link', label: 'Payment Link', probability: 61, expectedValue: 15249, rationale: '61% probability · ₹15,249 expected' },
        { intervention: 'send_whatsapp_reminder', label: 'WhatsApp Reminder', probability: 47, expectedValue: 11749, rationale: '47% probability · ₹11,749 expected' },
        { intervention: 'human_escalation', label: 'Human Escalation', probability: 74, expectedValue: 18499, rationale: '74% probability · ₹18,499 expected' },
      ],
      rationaleItems: [
        { text: 'First payment failure (clean history)', passed: true, type: 'history' },
        { text: 'Strong payment history (8 successful payments)', passed: true, type: 'history' },
        { text: 'High customer lifetime value (₹4.8L LTV)', passed: true, type: 'value' },
        { text: 'Retry limit available (0/2 attempts used)', passed: true, type: 'guardrail' },
        { text: 'Optimal retry window (next business morning)', passed: true, type: 'timing' },
      ],
      status: 'pending',
      createdAt: '2026-08-21T11:43:00Z',
    },
    timeline: [
      {
        id: 'tl-1',
        timestamp: '13:42:01',
        actor: 'System',
        event: 'Payment failure detected',
        toolUsed: 'webhook_receiver',
        details: 'Received Razorpay failure webhook (code: INSUFFICIENT_FUNDS)',
        status: 'completed',
        state: 'ANALYZING',
      },
      {
        id: 'tl-2',
        timestamp: '13:42:02',
        actor: 'Reclaim Agent',
        event: 'Customer history retrieved',
        toolUsed: 'get_customer_profile',
        details: 'Fetched 8 successful past cycles, zero past failures. LTV: ₹4.8L.',
        status: 'completed',
        state: 'ANALYZING',
      },
      {
        id: 'tl-3',
        timestamp: '13:42:03',
        actor: 'Reclaim Agent',
        event: 'Expected Recovery Value calculated',
        toolUsed: 'calculate_recovery_probability',
        details: 'Model computed ₹20,499 expected recovery (82% prob) for Smart Retry vs ₹15,249 for payment link.',
        result: '82% probability · ₹20,499 ERV',
        status: 'completed',
        state: 'DECIDING',
      },
      {
        id: 'tl-4',
        timestamp: '13:43:00',
        actor: 'Reclaim Agent',
        event: 'Recovery strategy selected',
        toolUsed: 'select_intervention',
        details: 'Selected smart retry for tomorrow 10:00 AM within guardrails.',
        status: 'completed',
        state: 'WAITING',
      },
    ],
    guardrailChecks: {
      retryLimitPassed: true,
      contactLimitPassed: true,
      quietHoursPassed: true,
      recoveryWindowPassed: true,
      highValueApprovalRequired: false,
      idempotencyPassed: true,
      actionEligibilityPassed: true,
    },
  },

  // 2. Checkout Demo: Rahul Sharma (Checkout Abandoned -> Payment Link)
  {
    id: 'case-checkout-10301',
    customerId: 'cust-rahul',
    customer: DEMO_CUSTOMERS[1],
    paymentId: 'chk_sess_rahul_10301',
    revenueType: 'checkout',
    eventId: 'evt_chk_rahul_10301',
    payment: {
      id: 'chk_sess_rahul_10301',
      customerId: 'cust-rahul',
      amount: 12999,
      currency: 'INR',
      status: 'pending',
      failureReason: 'Payment page abandonment',
      attemptCount: 0,
      provider: 'Billing Simulator',
      createdAt: '2026-08-21T10:10:00Z',
      updatedAt: '2026-08-21T10:12:00Z',
    },
    amount: 12999,
    status: 'at_risk',
    riskScore: 'Medium',
    recoveryProbability: 68,
    rootCause: 'Payment page abandonment',
    recommendedAction: 'Send 1-click payment link via WhatsApp',
    interventionType: 'send_payment_link',
    currentAction: 'Pending customer outreach',
    nextAction: 'Deliver instant checkout payment link',
    attemptsUsed: 0,
    contactAttemptsUsed: 0,
    createdAt: '2026-08-21T10:10:00Z',
    updatedAt: '2026-08-21T10:12:00Z',
    checkoutDetails: {
      abandonmentPoint: 'Payment confirmation',
      sessionId: 'sess_99218',
      cartValue: 12999,
      timeSpentSeconds: 180,
    },
    decision: {
      id: 'dec-10301',
      caseId: 'case-checkout-10301',
      paymentId: 'chk_sess_rahul_10301',
      recommendedAction: 'Send 1-click payment link via WhatsApp',
      interventionType: 'send_payment_link',
      recoveryProbability: 68,
      expectedRecoveryValue: 8839,
      explanation: 'Customer reached payment confirmation but abandoned session. Dynamic 1-click payment link sent via preferred WhatsApp channel yields 68% conversion (₹8,839 ERV).',
      recoveryOptions: [
        { intervention: 'send_payment_link', label: 'Payment Link', probability: 68, expectedValue: 8839, rationale: '68% probability · ₹8,839 expected' },
        { intervention: 'send_whatsapp_reminder', label: 'WhatsApp Reminder', probability: 54, expectedValue: 7019, rationale: '54% probability · ₹7,019 expected' },
        { intervention: 'retry_checkout_session', label: 'Retry Session', probability: 42, expectedValue: 5459, rationale: '42% probability · ₹5,459 expected' },
      ],
      rationaleItems: [
        { text: 'Abandoned at payment confirmation step', passed: true, type: 'risk' },
        { text: 'Preferred channel: WhatsApp verified', passed: true, type: 'timing' },
        { text: 'Within single-contact limit (0/3 used)', passed: true, type: 'guardrail' },
      ],
      status: 'pending',
      createdAt: '2026-08-21T10:12:00Z',
    },
    timeline: [
      {
        id: 'tl-c1',
        timestamp: '10:10:05',
        actor: 'System',
        event: 'Checkout session abandoned',
        details: 'User dropped at Payment Confirmation (Session: sess_99218)',
        status: 'completed',
        state: 'ANALYZING',
      },
      {
        id: 'tl-c2',
        timestamp: '10:11:00',
        actor: 'Reclaim Agent',
        event: 'Diagnosis: Payment confirmation abandoned',
        toolUsed: 'analyze_failure',
        details: 'Evaluated abandonment telemetry. Selected 1-click payment link with active cart retention.',
        result: '68% probability · ₹8,839 ERV',
        status: 'completed',
        state: 'DECIDING',
      },
    ],
    guardrailChecks: {
      retryLimitPassed: true,
      contactLimitPassed: true,
      quietHoursPassed: true,
      recoveryWindowPassed: true,
      highValueApprovalRequired: false,
      idempotencyPassed: true,
      actionEligibilityPassed: true,
    },
  },

  // 3. Receivable Demo: Acme Technologies (Overdue Invoice -> Promise-to-Pay)
  {
    id: 'case-rec-10401',
    customerId: 'cust-acme-tech',
    customer: DEMO_CUSTOMERS[2],
    paymentId: 'inv_acme_10291',
    revenueType: 'receivable',
    eventId: 'evt_inv_acme_10291',
    payment: {
      id: 'inv_acme_10291',
      customerId: 'cust-acme-tech',
      amount: 48000,
      currency: 'INR',
      status: 'failed',
      failureReason: 'Invoice overdue',
      attemptCount: 1,
      provider: 'Billing Simulator',
      createdAt: '2026-08-03T09:00:00Z',
      updatedAt: '2026-08-21T09:00:00Z',
    },
    amount: 48000,
    status: 'at_risk',
    riskScore: 'High',
    recoveryProbability: 75,
    rootCause: 'Invoice overdue',
    recommendedAction: 'Send executive follow-up & setup Promise-to-Pay workflow',
    interventionType: 'promise_to_pay',
    currentAction: 'Awaiting customer response / payment commitment',
    nextAction: 'Verify Promise-to-Pay settlement',
    scheduledTime: 'Tomorrow, 10:00 AM',
    attemptsUsed: 0,
    contactAttemptsUsed: 1,
    createdAt: '2026-08-03T09:00:00Z',
    updatedAt: '2026-08-21T09:00:00Z',
    receivableDetails: {
      invoiceId: 'INV-10291',
      daysOverdue: 18,
      dueDate: '2026-08-03T00:00:00Z',
      promiseToPay: {
        amount: 48000,
        promisedDate: '2026-08-25',
        status: 'promised',
        createdAt: '2026-08-21T09:00:00Z',
      },
    },
    decision: {
      id: 'dec-10401',
      caseId: 'case-rec-10401',
      paymentId: 'inv_acme_10291',
      recommendedAction: 'Executive follow-up with Promise-to-Pay tracking',
      interventionType: 'promise_to_pay',
      recoveryProbability: 75,
      expectedRecoveryValue: 36000,
      explanation: 'Enterprise invoice overdue by 18 days. Established customer with ₹12.5L LTV. Promise-to-Pay commitment of ₹48,000 tracked autonomously.',
      recoveryOptions: [
        { intervention: 'promise_to_pay', label: 'Promise-to-Pay Tracking', probability: 75, expectedValue: 36000, rationale: '75% probability · ₹36,000 expected' },
        { intervention: 'send_followup', label: 'Follow-up Reminder', probability: 64, expectedValue: 30720, rationale: '64% probability · ₹30,720 expected' },
        { intervention: 'account_manager_escalation', label: 'AM Escalation', probability: 80, expectedValue: 38400, rationale: '80% probability · ₹38,400 expected' },
      ],
      rationaleItems: [
        { text: 'Invoice INV-10291 is 18 days overdue', passed: true, type: 'risk' },
        { text: 'Strong enterprise profile (12 cleared invoices)', passed: true, type: 'history' },
        { text: 'Promise-to-Pay logged for ₹48,000', passed: true, type: 'timing' },
      ],
      status: 'pending',
      createdAt: '2026-08-21T09:00:00Z',
    },
    timeline: [
      {
        id: 'tl-r1',
        timestamp: 'Aug 03, 09:00',
        actor: 'System',
        event: 'Invoice due date passed',
        details: 'Invoice INV-10291 marked overdue (Amount: ₹48,000)',
        status: 'completed',
        state: 'ANALYZING',
      },
      {
        id: 'tl-r2',
        timestamp: 'Aug 21, 09:00',
        actor: 'Reclaim Agent',
        event: 'Customer promised payment — Promise-to-Pay recorded',
        toolUsed: 'promise_to_pay',
        details: 'Customer committed to ₹48,000 settlement on Monday. Agent set automated ledger watcher.',
        result: 'Promise-to-Pay active (₹48,000)',
        status: 'completed',
        state: 'WAITING',
      },
    ],
    guardrailChecks: {
      retryLimitPassed: true,
      contactLimitPassed: true,
      quietHoursPassed: true,
      recoveryWindowPassed: true,
      highValueApprovalRequired: false,
      idempotencyPassed: true,
      actionEligibilityPassed: true,
    },
  },

  // 4. Payment: Nova Systems (Card Expired)
  {
    id: 'case-nova-10292',
    customerId: 'cust-nova',
    customer: DEMO_CUSTOMERS[3],
    paymentId: 'pay_rzp_nova_10292',
    revenueType: 'payment',
    eventId: 'evt_pay_nova_10292',
    amount: 15499,
    status: 'recovering',
    riskScore: 'Medium',
    recoveryProbability: 76,
    rootCause: 'Card expired',
    recommendedAction: 'Send payment method update link via WhatsApp',
    interventionType: 'request_payment_method_update',
    currentAction: 'Waiting for card update',
    nextAction: 'Auto-charge updated card upon submission',
    attemptsUsed: 1,
    contactAttemptsUsed: 1,
    createdAt: '2026-08-21T09:15:00Z',
    updatedAt: '2026-08-21T09:20:00Z',
    payment: {
      id: 'pay_rzp_nova_10292',
      customerId: 'cust-nova',
      amount: 15499,
      currency: 'INR',
      status: 'failed',
      failureReason: 'Card expired',
      attemptCount: 1,
      provider: 'Razorpay Sandbox',
      createdAt: '2026-08-21T09:15:00Z',
      updatedAt: '2026-08-21T09:20:00Z',
    },
    decision: {
      id: 'dec-10292',
      caseId: 'case-nova-10292',
      paymentId: 'pay_rzp_nova_10292',
      recommendedAction: 'Request payment method update',
      interventionType: 'request_payment_method_update',
      recoveryProbability: 76,
      expectedRecoveryValue: 11779,
      explanation: 'Card expiry confirmed by gateway. Direct retry would fail; sending secure 1-click update link has 76% conversion within 4 hours.',
      recoveryOptions: [
        { intervention: 'request_payment_method_update', label: 'Method Update Link', probability: 76, expectedValue: 11779, rationale: '76% probability · ₹11,779 ERV' },
        { intervention: 'generate_payment_link', label: 'UPI Payment Link', probability: 58, expectedValue: 8989, rationale: '58% probability · ₹8,989 ERV' },
        { intervention: 'retry_payment', label: 'Naive Retry', probability: 10, expectedValue: 1549, rationale: '10% probability · Will fail' },
      ],
      rationaleItems: [
        { text: 'Card expiration confirmed by gateway', passed: true, type: 'risk' },
        { text: '14 successful past payments on file', passed: true, type: 'history' },
        { text: 'Contact limit within guardrails (1/3)', passed: true, type: 'guardrail' },
      ],
      status: 'executing',
      createdAt: '2026-08-21T09:16:00Z',
    },
    timeline: [
      {
        id: 'tl-n1',
        timestamp: '09:15:10',
        actor: 'System',
        event: 'Payment failure detected',
        toolUsed: 'webhook_receiver',
        details: 'Card expired (07/26)',
        status: 'completed',
        state: 'ANALYZING',
      },
      {
        id: 'tl-n2',
        timestamp: '09:16:00',
        actor: 'Reclaim Agent',
        event: 'Generated secure payment method link',
        toolUsed: 'create_payment_link',
        details: 'Created Razorpay compliant update token',
        status: 'completed',
        state: 'ACTING',
      },
      {
        id: 'tl-n3',
        timestamp: '09:16:30',
        actor: 'Reclaim Agent',
        event: 'WhatsApp notification dispatched',
        toolUsed: 'send_whatsapp_message',
        details: 'Sent 1-click payment update link to Ananya Deshmukh',
        status: 'completed',
        state: 'WAITING',
      },
    ],
    guardrailChecks: {
      retryLimitPassed: true,
      contactLimitPassed: true,
      quietHoursPassed: true,
      recoveryWindowPassed: true,
      highValueApprovalRequired: false,
      idempotencyPassed: true,
      actionEligibilityPassed: true,
    },
  },

  // 5. Payment: Globex (Insufficient funds)
  {
    id: 'case-globex-10293',
    customerId: 'cust-globex',
    customer: DEMO_CUSTOMERS[4],
    paymentId: 'pay_rzp_globex_10293',
    revenueType: 'payment',
    eventId: 'evt_pay_globex_10293',
    amount: 48999,
    status: 'recovering',
    riskScore: 'Low',
    recoveryProbability: 72,
    rootCause: 'Insufficient funds',
    recommendedAction: 'Retry payment at 14:00 today',
    interventionType: 'retry_payment',
    currentAction: 'Scheduled retry queued',
    nextAction: 'Execute gateway retry',
    attemptsUsed: 0,
    contactAttemptsUsed: 0,
    createdAt: '2026-08-21T08:30:00Z',
    updatedAt: '2026-08-21T08:35:00Z',
    payment: {
      id: 'pay_rzp_globex_10293',
      customerId: 'cust-globex',
      amount: 48999,
      currency: 'INR',
      status: 'failed',
      failureReason: 'Insufficient funds',
      attemptCount: 1,
      provider: 'Razorpay Sandbox',
      createdAt: '2026-08-21T08:30:00Z',
      updatedAt: '2026-08-21T08:35:00Z',
    },
    decision: {
      id: 'dec-10293',
      caseId: 'case-globex-10293',
      paymentId: 'pay_rzp_globex_10293',
      recommendedAction: 'Retry payment at 14:00 today',
      interventionType: 'retry_payment',
      recoveryProbability: 72,
      expectedRecoveryValue: 35279,
      explanation: 'High value client with regular afternoon clearing cycles. Automated retry scheduled for 2:00 PM.',
      rationaleItems: [
        { text: 'LTV ₹6.9L enterprise tier', passed: true, type: 'value' },
        { text: 'Zero previous unpaid defaults', passed: true, type: 'history' },
        { text: 'Within single-attempt retry limit', passed: true, type: 'guardrail' },
      ],
      status: 'approved',
      createdAt: '2026-08-21T08:32:00Z',
    },
    timeline: [
      {
        id: 'tl-g1',
        timestamp: '08:30:12',
        actor: 'System',
        event: 'Payment failed at gateway',
        details: 'Insufficient funds reported',
        status: 'completed',
        state: 'ANALYZING',
      },
      {
        id: 'tl-g2',
        timestamp: '08:32:00',
        actor: 'Reclaim Agent',
        event: 'Retry scheduled for 14:00',
        toolUsed: 'retry_payment',
        details: 'Calculated optimal clearing hour',
        status: 'completed',
        state: 'WAITING',
      },
    ],
    guardrailChecks: {
      retryLimitPassed: true,
      contactLimitPassed: true,
      quietHoursPassed: true,
      recoveryWindowPassed: true,
      highValueApprovalRequired: false,
      idempotencyPassed: true,
      actionEligibilityPassed: true,
    },
  },

  // 6. Payment: QuantLog (Invoice Overdue -> Recovered)
  {
    id: 'case-quantlog-10288',
    customerId: 'cust-quantlog',
    customer: DEMO_CUSTOMERS[7],
    paymentId: 'pay_rzp_quantlog_10288',
    revenueType: 'payment',
    eventId: 'evt_pay_quantlog_10288',
    amount: 89000,
    status: 'recovered',
    riskScore: 'Low',
    recoveryProbability: 91,
    rootCause: 'Invoice overdue',
    recommendedAction: 'WhatsApp reminder with 1-click RTGS/UPI link',
    interventionType: 'send_whatsapp_reminder',
    currentAction: 'Payment successful',
    nextAction: 'Workflow stopped',
    attemptsUsed: 1,
    contactAttemptsUsed: 1,
    recoveredAmount: 89000,
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-08-20T14:22:00Z',
    payment: {
      id: 'pay_rzp_quantlog_10288',
      customerId: 'cust-quantlog',
      amount: 89000,
      currency: 'INR',
      status: 'success',
      failureReason: 'Invoice overdue',
      attemptCount: 1,
      provider: 'Razorpay Sandbox',
      createdAt: '2026-08-20T10:00:00Z',
      updatedAt: '2026-08-20T14:22:00Z',
    },
    decision: {
      id: 'dec-10288',
      caseId: 'case-quantlog-10288',
      paymentId: 'pay_rzp_quantlog_10288',
      recommendedAction: 'WhatsApp reminder with 1-click RTGS/UPI link',
      interventionType: 'send_whatsapp_reminder',
      recoveryProbability: 91,
      expectedRecoveryValue: 80990,
      explanation: 'Overdue invoice recovered within 4 hours of gentle WhatsApp reminder to Devika Rao.',
      rationaleItems: [
        { text: 'Customer verified active', passed: true, type: 'history' },
        { text: 'Direct WhatsApp preferred channel', passed: true, type: 'timing' },
      ],
      status: 'completed',
      createdAt: '2026-08-20T10:02:00Z',
      executedAt: '2026-08-20T10:05:00Z',
      outcome: 'Payment confirmed via NetBanking webhook. ₹89,000 recovered.',
      recoveredAmount: 89000,
    },
    timeline: [
      {
        id: 'tl-q1',
        timestamp: '10:00:00',
        actor: 'System',
        event: 'Invoice due date expired',
        details: 'Invoice #INV-2026-881 overdue by 2 days',
        status: 'completed',
        state: 'ANALYZING',
      },
      {
        id: 'tl-q2',
        timestamp: '10:05:00',
        actor: 'Reclaim Agent',
        event: 'WhatsApp invoice reminder sent',
        toolUsed: 'send_whatsapp_reminder',
        details: 'Delivered customized payment link to Devika Rao',
        status: 'completed',
        state: 'ACTING',
      },
      {
        id: 'tl-q3',
        timestamp: '14:22:15',
        actor: 'System',
        event: 'Payment webhook received: SUCCESS',
        toolUsed: 'verify_payment_outcome',
        details: '₹89,000 received via Razorpay NetBanking',
        result: '₹89,000 recovered',
        status: 'completed',
        state: 'RECOVERED',
      },
      {
        id: 'tl-q4',
        timestamp: '14:22:16',
        actor: 'Reclaim Agent',
        event: 'Workflow automatically stopped',
        toolUsed: 'stop_workflow',
        details: 'Recovery objective fulfilled. No further contact scheduled.',
        status: 'completed',
        state: 'STOPPED',
      },
    ],
    guardrailChecks: {
      retryLimitPassed: true,
      contactLimitPassed: true,
      quietHoursPassed: true,
      recoveryWindowPassed: true,
      highValueApprovalRequired: false,
      idempotencyPassed: true,
      actionEligibilityPassed: true,
    },
  },

  // 7. Payment: AlphaStream (Bank Decline -> Escalated)
  {
    id: 'case-alphastream-10280',
    customerId: 'cust-alphastream',
    customer: DEMO_CUSTOMERS[9],
    paymentId: 'pay_rzp_alpha_10280',
    revenueType: 'payment',
    eventId: 'evt_pay_alpha_10280',
    amount: 78000,
    status: 'escalated',
    riskScore: 'Critical',
    recoveryProbability: 34,
    rootCause: 'Bank decline',
    recommendedAction: 'Escalate to Senior CSM Karan Joshi for direct billing reconciliation',
    interventionType: 'human_escalation',
    currentAction: 'Assigned to Karan Joshi',
    nextAction: 'Manual executive resolution',
    attemptsUsed: 2,
    contactAttemptsUsed: 3,
    createdAt: '2026-08-19T08:00:00Z',
    updatedAt: '2026-08-20T16:00:00Z',
    payment: {
      id: 'pay_rzp_alpha_10280',
      customerId: 'cust-alphastream',
      amount: 78000,
      currency: 'INR',
      status: 'failed',
      failureReason: 'Bank decline',
      attemptCount: 2,
      provider: 'Razorpay Sandbox',
      createdAt: '2026-08-19T08:00:00Z',
      updatedAt: '2026-08-20T16:00:00Z',
    },
    decision: {
      id: 'dec-10280',
      caseId: 'case-alphastream-10280',
      paymentId: 'pay_rzp_alpha_10280',
      recommendedAction: 'Escalate to Senior CSM Karan Joshi',
      interventionType: 'human_escalation',
      recoveryProbability: 34,
      expectedRecoveryValue: 26520,
      explanation: 'Case reached guardrail boundaries (2 retries + 3 reminders completed). Autonomous agent stopped to prevent customer spam.',
      rationaleItems: [
        { text: 'Max retry limit reached (2/2)', passed: false, type: 'guardrail' },
        { text: 'Max contact attempts reached (3/3)', passed: false, type: 'guardrail' },
        { text: 'Escalation policy triggered', passed: true, type: 'guardrail' },
      ],
      status: 'escalated',
      createdAt: '2026-08-20T16:00:00Z',
    },
    timeline: [
      {
        id: 'tl-a1',
        timestamp: 'Aug 19, 08:00',
        actor: 'System',
        event: 'Payment failed (Attempt 1)',
        details: 'Bank decline on auto-debit',
        status: 'completed',
        state: 'ANALYZING',
      },
      {
        id: 'tl-a2',
        timestamp: 'Aug 19, 14:00',
        actor: 'Reclaim Agent',
        event: 'Smart retry executed (Attempt 2)',
        toolUsed: 'retry_payment',
        details: 'Retry returned: Insufficient limit on corporate card',
        status: 'failed',
        state: 'ACTING',
      },
      {
        id: 'tl-a3',
        timestamp: 'Aug 20, 16:00',
        actor: 'Reclaim Agent',
        event: 'Guardrail limit reached — Escalated to Human',
        toolUsed: 'escalate_case',
        details: 'Assigned to Karan Joshi. Autonomous agent safely paused.',
        status: 'completed',
        state: 'ESCALATED',
      },
    ],
    guardrailChecks: {
      retryLimitPassed: false,
      contactLimitPassed: false,
      quietHoursPassed: true,
      recoveryWindowPassed: true,
      highValueApprovalRequired: true,
      idempotencyPassed: true,
      actionEligibilityPassed: true,
    },
  },
];

// ─── Generate Full 200+ Cases Dataset (100+ Payments, 50+ Checkout, 50+ Receivables) ────

const SYNTHETIC_DATASET = generateSyntheticCases({
  totalCases: 210,
  scenarioMix: {
    payments: 52,    // ~110 payment cases
    checkout: 24,    // ~50 checkout cases
    receivables: 24, // ~50 receivable cases
  },
  seed: 1337,
});

// Merge showcase cases at top for immediate demo access
export const INITIAL_CASES: RecoveryCase[] = [
  ...SHOWCASE_CASES,
  ...SYNTHETIC_DATASET.filter((sc) => !SHOWCASE_CASES.some((sh) => sh.id === sc.id)),
];

// Compute Initial KPIs from case pool
const totalAtRisk = INITIAL_CASES.filter((c) => c.status === 'at_risk').reduce((sum, c) => sum + c.amount, 0);
const totalRecovering = INITIAL_CASES.filter((c) => c.status === 'recovering').reduce((sum, c) => sum + c.amount, 0);
const totalRecovered = INITIAL_CASES.filter((c) => c.status === 'recovered').reduce((sum, c) => sum + (c.recoveredAmount || c.amount), 0);
const activeCount = INITIAL_CASES.filter((c) => c.status === 'at_risk' || c.status === 'recovering').length;

export const INITIAL_KPIS: RecoveryKPIData = {
  revenueAtRisk: totalAtRisk || 1842000,
  recovering: totalRecovering || 684000,
  recovered: totalRecovered || 724000,
  recoveryRate: 41.2,
  activeCasesCount: activeCount || 143,
  trendVsLastMonth: 18.4,
  eventsProcessed: 1248,
  actionsTaken: 312,
};

export const DEMO_INTEGRATIONS: IntegrationSource[] = [
  {
    id: 'int-rzp',
    name: 'Razorpay Sandbox',
    type: 'payment',
    provider: 'Razorpay (Sandbox)',
    status: 'connected',
    isSandbox: true,
    description: 'Payment events, transaction status feeds, webhooks, and recovery opportunities.',
    eventsCount: 127,
    lastSync: 'Just now',
    iconName: 'CreditCard',
  },
  {
    id: 'int-billing',
    name: 'Reclaim Billing',
    type: 'billing',
    provider: 'Reclaim Engine (Billing)',
    status: 'connected',
    isSandbox: true,
    description: 'Subscriptions, invoices, renewals, and overdue payment detection.',
    eventsCount: 84,
    lastSync: '2m ago',
    iconName: 'FileText',
  },
  {
    id: 'int-bank',
    name: 'Business Bank — Sandbox',
    type: 'bank',
    provider: 'HDFC Bank (Sandbox •••• 4821)',
    status: 'connected',
    isSandbox: true,
    description: 'Transaction verification, bank clearance status, and financial context.',
    eventsCount: 184,
    lastSync: 'Just now',
    iconName: 'Building',
  },
  {
    id: 'int-email',
    name: 'Email Recovery Channel',
    type: 'channel',
    provider: 'Direct SMTP / SendGrid',
    status: 'connected',
    isSandbox: true,
    description: 'Automated high-deliverability payment reminders and recovery links.',
    eventsCount: 52,
    lastSync: '5m ago',
    iconName: 'Mail',
  },
  {
    id: 'int-wa',
    name: 'WhatsApp Sandbox',
    type: 'channel',
    provider: 'Meta Cloud API (Sandbox)',
    status: 'not_connected',
    isSandbox: true,
    description: 'Customer recovery messaging and interactive 1-click update links.',
    eventsCount: 0,
    lastSync: 'Never',
    iconName: 'MessageSquare',
  },
  {
    id: 'int-crm',
    name: 'HubSpot / Salesforce CRM',
    type: 'crm',
    provider: 'Salesforce (Mock)',
    status: 'not_connected',
    isSandbox: true,
    description: 'Synchronizes customer health scores, deal size, and account manager assignments.',
    eventsCount: 0,
    lastSync: 'Never',
    iconName: 'Users',
  },
];
